name: Publish to NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"  # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore CsConfUtil.sln

      - name: Build the project
        run: dotnet build CsConfUtil.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Create NuGet package
        run: dotnet pack src/CsConfUtil/CsConfUtil.csproj --configuration Release --output bin/Release

      - name: Push package to NuGet
        run: dotnet nuget push bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
